title: MyBlog
description: 我的随便写写的 Blog
url: "https://joysky77.github.io"
baseurl: "/MyBlog"
lang: zh-CN
timezone: Asia/Shanghai

markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/
future: true

author:
  name: joysky77

comments:
  provider: utterances
  repo: joysky77/MyBlog
  issue_term: pathname
  label: blog-comment
  theme: github-dark

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - _drafts
