# 基本配置
title: MyBlog
description: 随便谢谢
url: "https://github.com/joysky77/MyBlog/"
baseurl: ""

# Jekyll 配置
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/

# 允许未来日期文章
future: true
timezone: Asia/Shanghai

# 插件
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
